# Generated by Django 5.1 on 2025-02-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bolg_user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/profile_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/post_images/"
            ),
        ),
    ]
